// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolRowingApp.Infrastructure.Data;

#nullable disable

namespace SchoolRowingApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250920130429_UseCompositeKeyForMembershipPeriod")]
    partial class UseCompositeKeyForMembershipPeriod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolRowingApp.Domain.Athletes.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Athletes", (string)null);
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Athletes.AthletePayer", b =>
                {
                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PayerType")
                        .HasColumnType("integer");

                    b.HasKey("AthleteId", "PayerId");

                    b.HasIndex("PayerId");

                    b.ToTable("AthletePayers", (string)null);
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Membership.AthleteMembership", b =>
                {
                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<int>("MembershipPeriodYear")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipPeriodMonth")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AthleteId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ParticipationCoefficient")
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("AthleteId", "MembershipPeriodYear", "MembershipPeriodMonth");

                    b.HasIndex("AthleteId1");

                    b.HasIndex("MembershipPeriodYear", "MembershipPeriodMonth");

                    b.ToTable("AthleteMemberships", "bob");
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Membership.MembershipPeriod", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Year", "Month");

                    b.ToTable("MembershipPeriods", "bob", t =>
                        {
                            t.HasCheckConstraint("CK_BaseFee", "BaseFee >= 0");

                            t.HasCheckConstraint("CK_Month", "Month >= 1 AND Month <= 12");

                            t.HasCheckConstraint("CK_Year", "Year >= 2020 AND Year <= 2100");
                        });
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Payments.Payer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Payers", (string)null);
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Athletes.AthletePayer", b =>
                {
                    b.HasOne("SchoolRowingApp.Domain.Athletes.Athlete", "Athlete")
                        .WithMany("AthletePayers")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolRowingApp.Domain.Payments.Payer", "Payer")
                        .WithMany("AthletePayers")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Membership.AthleteMembership", b =>
                {
                    b.HasOne("SchoolRowingApp.Domain.Athletes.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolRowingApp.Domain.Athletes.Athlete", null)
                        .WithMany("AthleteMemberships")
                        .HasForeignKey("AthleteId1");

                    b.HasOne("SchoolRowingApp.Domain.Membership.MembershipPeriod", "MembershipPeriod")
                        .WithMany("AthleteMemberships")
                        .HasForeignKey("MembershipPeriodYear", "MembershipPeriodMonth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("MembershipPeriod");
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Athletes.Athlete", b =>
                {
                    b.Navigation("AthleteMemberships");

                    b.Navigation("AthletePayers");
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Membership.MembershipPeriod", b =>
                {
                    b.Navigation("AthleteMemberships");
                });

            modelBuilder.Entity("SchoolRowingApp.Domain.Payments.Payer", b =>
                {
                    b.Navigation("AthletePayers");
                });
#pragma warning restore 612, 618
        }
    }
}
